flight_num = input('номер рейса: ')
company_name_ru = input('название авиакомпании (на русском языке): ')
company_name_en = input('название авиакомпании (на английском языке): ')
arrival_point_ru = input('город прилета (на русском языке): ')
arrival_point_en = input('город прилета (на английском языке): ')
print(f'Заканчивается посадка на рейс {flight_num} {company_name_ru} до {arrival_point_ru}')
print(f'This is the final boarding call for {company_name_en} flight {flight_num} to {arrival_point_en}')